# Generated by Django 4.2.8 on 2024-01-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('photo', models.ImageField(default='SOME STRING', upload_to='result_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gray', models.ImageField(default='Not Set', upload_to='')),
            ],
        ),
    ]
